Quickstart=1
read_config_descriptions=yes
write_logfile=no
default_line_mode=1
rctrl_as_ramiga=no
gui_joystick_control=yes
input_default_mouse_speed=100
input_keyboard_as_joystick_stop_keypresses=no
default_open_gui_key=F12
default_quit_key=
default_ar_key=Pause
default_fullscreen_toggle_key=
default_horizontal_centering=no
default_vertical_centering=no
default_scaling_method=-1
default_gfx_autoresolution=0
default_frameskip=no
perf_log=no
slow_host_warning=yes
default_disable_cycle_exact=no
default_quickstart_compatibility=0
default_correct_aspect_ratio=yes
default_auto_crop=no
default_width=720
default_height=568
default_fullscreen_mode=0
default_stereo_separation=7
default_sound_frequency=44100
default_sound_buffer=3072
default_joystick_deadzone=33
default_retroarch_quit=yes
default_retroarch_menu=yes
default_retroarch_reset=no
default_retroarch_vkbd=no
default_controller1=joy0
default_controller2=joy2
default_controller3=
default_controller4=
default_mouse1=mouse
default_mouse2=none
default_whd_buttonwait=no
default_whd_showsplash=yes
default_whd_configdelay=0
default_whd_writecache=no
default_whd_quit_on_exit=no
use_jst_instead_of_whd=no
disable_shutdown_button=yes
allow_display_settings_from_xml=yes
default_soundcard=0
default_onscreen_joystick=no
default_vkbd_enabled=no
default_vkbd_hires=no
default_vkbd_exit=no
default_vkbd_language=US
default_vkbd_style=Original
default_vkbd_transparency=0
default_vkbd_toggle=guide
gui_theme=Default.theme
shader=none
shader_rtg=none
use_bezel=no
use_custom_bezel=no
custom_bezel=none
update_check=1
update_channel=0
skipped_version=
last_update_check=
base_content_path=
retroarch_config=/root/Amiberry/Configurations/retroarch.cfg
floppy_sounds_dir=/usr/share/amiberry/data/floppy_sounds/
plugins_dir=/usr/lib/amiberry
config_path=/root/Amiberry/Configurations
controllers_path=/root/.local/share/amiberry/Controllers/
whdboot_path=/root/.local/share/amiberry/WHDBoot/
whdload_arch_path=/root/Amiberry/LHA/
floppy_path=/root/Amiberry/Floppies/
harddrive_path=/root/Amiberry/HardDrives/
cdrom_path=/root/Amiberry/CDROMs/
logfile_path=/root/Amiberry/Amiberry.log
rom_path=/root/Amiberry/ROMs/
rp9_path=/root/Amiberry/RP9/
saveimage_dir=/root/.local/share/amiberry/
savestate_dir=/root/Amiberry/SaveStates/
ripper_path=/root/.local/share/amiberry/Ripper/
inputrecordings_dir=/root/.local/share/amiberry/InputRecordings/
screenshot_dir=/root/Amiberry/Screenshots/
nvram_dir=/root/.local/share/amiberry/NVRAM/
video_dir=/root/.local/share/amiberry/Videos/
themes_path=/root/Amiberry/Visuals/Themes
shaders_path=/root/Amiberry/Visuals/Shaders
bezels_path=/root/Amiberry/Visuals/Bezels
MRUDiskList=0
MRUCDList=0
MRUWHDLoadList=0
