# =============================================================================
# wpa_supplicant.conf — Configuración WiFi
# Editar SSID y contraseña antes de compilar
#
# Para generar el hash de la contraseña:
#   wpa_passphrase "MI_RED" "MI_PASSWORD" >> /etc/wpa_supplicant.conf
# =============================================================================

ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0
update_config=1
country=ES

network={
	ssid="CAMBIAR_SSID"
	psk="CAMBIAR_PASSWORD"
	key_mgmt=WPA-PSK
	proto=RSN
	pairwise=CCMP
	group=CCMP
}
