################################################################################
#
# fastfetch
#
################################################################################

FASTFETCH_VERSION = 2.63.1
FASTFETCH_SITE = $(call github,fastfetch-cli,fastfetch,$(FASTFETCH_VERSION))
FASTFETCH_LICENSE = MIT
FASTFETCH_LICENSE_FILES = LICENSE
FASTFETCH_INSTALL_STAGING = NO
FASTFETCH_INSTALL_TARGET = YES

FASTFETCH_DEPENDENCIES = host-pkgconf

# CMake build
FASTFETCH_CONF_OPTS = \
	-DENABLE_VULKAN=OFF \
	-DENABLE_WAYLAND=OFF \
	-DENABLE_X11=OFF \
	-DENABLE_XCB=OFF \
	-DENABLE_XFCONF=OFF \
	-DENABLE_GIO=OFF \
	-DENABLE_DCONF=OFF \
	-DENABLE_DBUS=OFF \
	-DENABLE_XRANDR=OFF \
	-DENABLE_DRM=OFF \
	-DENABLE_IMAGEMAGICK6=OFF \
	-DENABLE_IMAGEMAGICK7=OFF \
	-DENABLE_CHAFA=OFF \
	-DENABLE_EGL=OFF \
	-DENABLE_GLX=OFF \
	-DENABLE_OSMESA=OFF \
	-DENABLE_OPENCL=OFF \
	-DENABLE_LIBNM=OFF \
	-DENABLE_PULSE=OFF \
	-DENABLE_DDCUTIL=OFF \
	-DENABLE_DIRECTX_HEADERS=OFF \
	-DENABLE_THREADS=ON \
	-DBUILD_TESTS=OFF \
	-DBUILD_FLASHFETCH=OFF

$(eval $(cmake-package))
