[global]
    workgroup = WORKGROUP
    server string = Armiga
    netbios name = h700
    security = user
    map to guest = Bad User
    guest account = root
    log file = /dev/null
    max log size = 0
    load printers = no
    printing = bsd
    printcap name = /dev/null
    disable spoolss = yes

[amiga_data]
    path = /media/amiga_data
    browseable = yes
    read only = no
    guest ok = yes
    force user = root
