[global]
    workgroup = WORKGROUP
    server string = armiga
    netbios name = armiga
    security = user
    log file = /dev/null
    max log size = 0
    load printers = no
    printing = bsd
    printcap name = /dev/null
    disable spoolss = yes

[amiga_data]
    path = /media/amiga_data
    browseable = yes
    read only = no
    valid users = root
    force user = root
