#!/bin/sh
# DESC_ES: Chequeo completo del sistema, genera informe markdown detallado
# DESC_EN: Full system check, generates a detailed markdown report

OUT_DIR="/media/amiga_data/diagnostics"
TS="$(date +%Y%m%d_%H%M%S)"
OUT_FILE="$OUT_DIR/armiga_diag_${TS}.md"
mkdir -p "$OUT_DIR"

RELEASE_FILE="/etc/armiga-release"
ARMIGA_VERSION="$(grep '^ARMIGA_VERSION=' "$RELEASE_FILE" 2>/dev/null | cut -d= -f2)"
BUILD_NUMBER="$(grep '^BUILD_NUMBER=' "$RELEASE_FILE" 2>/dev/null | cut -d= -f2)"
BUILD_DATE="$(grep '^BUILD_DATE=' "$RELEASE_FILE" 2>/dev/null | cut -d= -f2-)"
KERNEL_VERSION="$(grep '^KERNEL_VERSION=' "$RELEASE_FILE" 2>/dev/null | cut -d= -f2)"

CPU_GOV="$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor 2>/dev/null)"
CPU_CUR="$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq 2>/dev/null)"
CPU_MAX="$(cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq 2>/dev/null)"
CPU_TEMP_RAW="$(cat /sys/class/thermal/thermal_zone0/temp 2>/dev/null)"
CPU_TEMP="?"
[ -n "$CPU_TEMP_RAW" ] && CPU_TEMP="$(echo "scale=1; $CPU_TEMP_RAW / 1000" | bc 2>/dev/null)"

WIFI_STATE="$(cat /sys/class/net/wlan0/operstate 2>/dev/null)"
WIFI_IP="$(ip -4 addr show wlan0 2>/dev/null | grep -oE 'inet [0-9.]+' | cut -d' ' -f2)"
WIFI_MAC="$(cat /sys/class/net/wlan0/address 2>/dev/null)"
WIFI_SIGNAL="$(cat /proc/net/wireless 2>/dev/null | awk 'NR==3{print $4}')"

BT_ENABLED="$(grep '^BT_ENABLED=' /media/amiga_data/armiga.cfg 2>/dev/null | cut -d= -f2)"
BT_CONNECTED="$(cat /tmp/armiga-bt-connected.txt 2>/dev/null)"

BATTERY_PCT="$(cat /sys/class/power_supply/battery/capacity 2>/dev/null)"

RAM_INFO="$(free -m 2>/dev/null | awk 'NR==2{printf "%s MB usados / %s MB totales", $3, $2}')"

DISK_DATA="$(df -h /media/amiga_data 2>/dev/null | awk 'NR==2{printf "%s usados / %s totales (%s libre)", $3, $2, $4}')"
DISK_ROOT="$(df -h / 2>/dev/null | awk 'NR==2{printf "%s usados / %s totales (%s libre)", $3, $2, $4}')"

UPTIME_INFO="$(uptime 2>/dev/null)"

MOD_WIFI="$(lsmod 2>/dev/null | grep -c rtw88)"; MOD_WIFI="${MOD_WIFI:-0}"
MOD_JOYPAD="$(lsmod 2>/dev/null | grep -c rocknix_singleadc_joypad)"; MOD_JOYPAD="${MOD_JOYPAD:-0}"

OVERLAY_USR="$(mount 2>/dev/null | grep -c 'on /usr type overlay')"; OVERLAY_USR="${OVERLAY_USR:-0}"

LAUNCHER_RUNNING="$(ps 2>/dev/null | grep -c '/usr/bin/armiga-launcher$')"; LAUNCHER_RUNNING="${LAUNCHER_RUNNING:-0}"
ZOMBIES="$(ps 2>/dev/null | awk '$0 ~ /Z/{c++} END{print c+0}')"; ZOMBIES="${ZOMBIES:-0}"

ARMIGA_CFG_EXISTS="No"
[ -f /media/amiga_data/armiga.cfg ] && ARMIGA_CFG_EXISTS="Si"
RETROARCH_CFG_EXISTS="No"
[ -f /media/amiga_data/retroarch/retroarch.cfg ] && RETROARCH_CFG_EXISTS="Si"

DMESG_ERRORS="$(dmesg -l err,crit,alert,emerg 2>/dev/null | tail -n 30)"
[ -z "$DMESG_ERRORS" ] && DMESG_ERRORS="(ninguno)"

{
echo "# Informe de Diagnostico ARMIGA"
echo ""
echo "**Generado:** $(date '+%Y-%m-%d %H:%M:%S')"
echo ""
echo "## Sistema"
echo ""
echo "| Campo | Valor |"
echo "|---|---|"
echo "| Version ARMIGA | ${ARMIGA_VERSION:-?} |"
echo "| Build | #${BUILD_NUMBER:-?} (${BUILD_DATE:-?}) |"
echo "| Kernel | ${KERNEL_VERSION:-?} |"
echo "| Uptime | ${UPTIME_INFO:-?} |"
echo "| Overlay /usr montado | $([ "$OVERLAY_USR" -gt 0 ] && echo "SI (modo hot-iteration activo)" || echo "No") |"
echo ""
echo "## CPU y Temperatura"
echo ""
echo "| Campo | Valor |"
echo "|---|---|"
echo "| Governor | ${CPU_GOV:-?} |"
CPU_CUR_MHZ="?"; [ -n "$CPU_CUR" ] && CPU_CUR_MHZ="$((CPU_CUR/1000)) MHz"
CPU_MAX_MHZ="?"; [ -n "$CPU_MAX" ] && CPU_MAX_MHZ="$((CPU_MAX/1000)) MHz"
echo "| Frecuencia actual | ${CPU_CUR_MHZ} |"
echo "| Frecuencia maxima | ${CPU_MAX_MHZ} |"
echo "| Temperatura | ${CPU_TEMP}C |"
echo ""
echo "## Memoria y Almacenamiento"
echo ""
echo "| Campo | Valor |"
echo "|---|---|"
echo "| RAM | ${RAM_INFO:-?} |"
echo "| Disco (amiga_data) | ${DISK_DATA:-?} |"
echo "| Disco (raiz) | ${DISK_ROOT:-?} (normal en rootfs de solo lectura) |"
echo ""
echo "## Red y Bluetooth"
echo ""
echo "| Campo | Valor |"
echo "|---|---|"
echo "| WiFi estado | ${WIFI_STATE:-?} |"
echo "| WiFi IP | ${WIFI_IP:-(sin IP)} |"
echo "| WiFi MAC | ${WIFI_MAC:-?} |"
echo "| WiFi señal | ${WIFI_SIGNAL:-?} |"
echo "| Bluetooth habilitado | $([ "$BT_ENABLED" = "1" ] && echo "Si" || echo "No") |"
echo "| Bluetooth conectado a | ${BT_CONNECTED:-(ninguno)} |"
echo ""
echo "## Bateria"
echo ""
echo "| Campo | Valor |"
echo "|---|---|"
echo "| Nivel | ${BATTERY_PCT:-?}% |"
echo ""
echo "## Modulos de Kernel Criticos"
echo ""
echo "| Modulo | Cargado |"
echo "|---|---|"
echo "| WiFi (rtw88) | $([ "$MOD_WIFI" -gt 0 ] && echo "Si" || echo "NO - POSIBLE FALLO") |"
echo "| Joypad (rocknix_singleadc) | $([ "$MOD_JOYPAD" -gt 0 ] && echo "Si" || echo "NO - POSIBLE FALLO") |"
echo ""
echo "## Configuracion"
echo ""
echo "| Campo | Valor |"
echo "|---|---|"
echo "| armiga.cfg existe | ${ARMIGA_CFG_EXISTS} |"
echo "| retroarch.cfg existe | ${RETROARCH_CFG_EXISTS} |"
echo ""
echo "## Procesos"
echo ""
echo "| Campo | Valor |"
echo "|---|---|"
echo "| armiga-launcher corriendo | $([ "$LAUNCHER_RUNNING" -gt 0 ] && echo "Si ($LAUNCHER_RUNNING proceso/s)" || echo "NO - POSIBLE FALLO") |"
echo "| Procesos zombie | ${ZOMBIES:-0} |"
echo ""
echo "## Errores recientes del Kernel (dmesg, ultimas 30 lineas relevantes)"
echo ""
echo '```'
echo "$DMESG_ERRORS"
echo '```'
} > "$OUT_FILE"

echo "Informe generado:"
echo "$OUT_FILE"
