#!/bin/sh
# S15modules — Carga de módulos del kernel
case "$1" in
    start)
        printf "Loading kernel modules: "
        for mod in bluetooth btrtl hci_uart; do
            modprobe "$mod" 2>/dev/null && echo -n "$mod "
        done
        insmod /lib/modules/7.0.11/rocknix-singleadc-joypad.ko && echo -n "rocknix-joypad "
        echo "OK"
        ;;
    stop)
        echo "OK"
        ;;
    restart)
        "$0" stop
        "$0" start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
