#!/bin/sh
# S29alsa — Restaurar niveles ALSA desde rootfs
case "$1" in
    start)
        amixer sset 'Line Out' 100% on
        amixer sset 'DAC' 100% on
        ;;
    stop|restart)
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
