#!/bin/sh
# S29alsa — Restaurar/guardar niveles ALSA
ALSA_STATE="/media/amiga_data/alsa/asound.state"

case "$1" in
    start)
        if [ -f "$ALSA_STATE" ]; then
            alsactl -f "$ALSA_STATE" restore
        else
            amixer sset "Line Out" 80% on
            amixer sset "DAC" 80% on
            amixer sset "Speaker" on
        fi
        ;;
    stop)
        mkdir -p "$(dirname $ALSA_STATE)"
        alsactl -f "$ALSA_STATE" store
        ;;
    restart)
        "$0" stop
        "$0" start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
